<div class="box grid_12">
    <div class="box-head"><h2>System</h2></div>
    <div class="box-content">
        <div class="state-button-wrapper">
            <a class="button big grey" href="/system/showadminlog">Show Admin Log</a>
            <a class="button big grey" href="/system/databasebackup">Database backup</a>
            <a class="button big grey" href="/system/showdeletedprojects">Show deleted projects</a>
            <a class="button big grey" href="/system/showdeletedtasks">Show deleted tasks</a>
            <a class="button big grey" href="/system/showdeletedusers">Show deleted users</a>
        </div>
    </div>
</div>