<div class="box grid_12">
    <div class="box-head"><h2>System</h2></div>
    <div class="box-content">
        <div class="state-button-wrapper">
            <a class="button big grey" href="/system/showadminlog">Show Admin Log</a>
            <a class="button big grey" href="/system/databasebackup">Database backup</a>
            <a class="button big grey" href="/system/showdeletedprojects">Show deleted projects</a>
            <a class="button big grey" href="/system/showdeletedtasks">Show deleted tasks</a>
            <a class="button big grey" href="/system/showdeletedusers">Show deleted users</a>
            <a class="button big grey" href="/system/settings">Edit application settings</a>
        </div>
    </div>
</div>
<div class="box grid_12">
    <div class="box-head"><h2>Deleted Projects</h2></div>
    <div class="box-content no-pad">
        <input type="hidden" id="tk" name="tk" value="{echo $token}" />
        <table class="stdtable display">
            <thead>
                <tr>
                    <th>Title</th><th>Client</th>
                    <th>State</th><th>Manager</th>
                    <th>Created</th><th>Modified</th><th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                {if !empty($projects)}
                    {foreach $project in $projects}
                        <tr>
                            <td>{echo $project->title}</td>
                            <td>{echo $project->companyName}</td>
                            <td>{echo $project->stateTitle}</td>
                            <td>{echo $project->mFname." ".$project->mFname}</td>
                            <td>{echo $project->getCreated()}</td>
                            <td>{echo $project->getModified()}</td>
                            <td>
                                <a class="button-task ajax-button" href="/project/undelete/{echo $project->getId()}">Undelete Project</a>
                            </td>
                        </tr>
                    {/foreach}
                {/if}
            </tbody>
        </table>
    </div>
</div>