<div class="box-content">
    <form class="form" action="/task/delete/{echo $task->getId()}" method="post">
        <input type="hidden" name="csrf" value="{echo $token}" />
        <div class="form-row">
            <p class="form-label">Task name*</p>
            <div class="form-item">
                {echo $task->getTitle()}
            </div>
        </div>
        <div class="form-row">
            <p class="form-label">Description*</p>
            <div class="form-item">
                {echo $task->getDescription()}
            </div>
        </div>
        <div class="form-row">
            <div class="form-item">
                <input type="submit" class="button red" name="submitDeleteTask" value="Delete task"/>
            </div>
        </div>
    </form>
</div>