<div class="box grid_12">
    <div class="box-head"><h2>Edit task</h2></div>
    <div class="box-content">
        <form class="form" action="#" method="post">
            <input type="hidden" name="csrf" value="{echo $token}" />
            <div class="form-row">
                <p class="form-label">Title*</p>
                <div class="form-item">
                    <input type="text" name="title" value="{echo $task->getTitle()}" />
                </div>
                {if isset($errors["title"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["title"])}</p>
                {/if}
                {if isset($errors["urlKey"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["urlKey"])}</p>
                {/if}
            </div>
            <div class="form-row">
                <p class="form-label">State*</p>
                <div class="form-item">
                    <select name="state">
                        {if !empty($states)}
                            {foreach $state in $states}
                                {script $s = ""}
                                {if $task->getStateId() == $state->getId()}
                                    {script $s = "selected"}
                                {/if}
                                <option value="{echo $state->getId()}" {echo $s}>{echo $state->getTitle()}</option>
                            {/foreach}
                        {/if}
                    </select>
                </div>
                {if isset($errors["stateId"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["stateId"])}</p>
                {/if}
            </div>
            <div class="form-row">
                <p class="form-label">Description*</p>
                <div class="form-item">
                    <textarea cols="85" rows="5" name="description" id="ckeditor">{echo $task->getDescription()}</textarea>
                </div>
                {if isset($errors["description"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["description"])}</p>
                {/if}
            </div>
            <div class="form-row">
                <p class="form-label">Created by</p>
                <div class="form-item">
                    {echo $task->cFname." ".$task->cLname}
                </div>
            </div>
            <div class="form-row">
                <p class="form-label">Assign to*</p>
                <div class="form-item">
                    <select name="assignTo">
                        {if !empty($users)}
                            {foreach $user in $users}
                                {script $s=""}
                                {if $user->getId()==$task->getAssignedTo()}
                                    {script $s="selected=selected"}
                                {/if}
                                <option value="{echo $user->getId()}" {echo $s}>
                                    {echo $user->getFirstname() . " " . $user->getLastname()}
                                </option>
                            {/foreach}
                        {/if}
                    </select>
                </div>
                {if isset($errors["assignTo"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["assignTo"])}</p>
                {/if}
            </div>
            <div class="form-row">
                <p class="form-label">Priority *</p>
                <div class="form-item">
                    <select name="priority">
                        {for $i=0 $i<6 $i++}
                            {if $i == $task->priority}
                                <option value="$i" selected="selected">{echo $i}</option>
                            {/if}
                            {else}
                                <option value="$i">{echo $i}</option>
                            {/else}
                        {/for}
                    </select>
                </div>
                {if isset($errors["priority"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["priority"])}</p>
                {/if}
            </div>
            <div class="form-row">
                <p class="form-label">Active</p>
                <div class="form-item">
                    <select name="active">
                    {if $task->active}
                    <option value="0">Inactive</option>
                    <option value="1" selected>Active</option>
                    {/if}
                    {else}
                    <option value="0" selected>Inactive</option>
                    <option value="1">Active</option>
                    {/else}
                </select>
                </div>
            </div>
            <div class="form-row">
                <p class="form-label">Created</p>
                <div class="form-item">
                    {echo $task->created}
                </div>
            </div>
            <div class="form-row">
                <p class="form-label">Modified</p>
                <div class="form-item">
                    {echo $task->modified}
                </div>
            </div>
            <div class="form-row">
                <div class="form-item">
                    <input type="button" class="button grey" onclick="history.back();" value="Back">
                </div>
            </div>
            <div class="form-row">
                <div class="form-item">
                    <input type="submit" class="button blue" name="submitEditTask" value="Save changes"/>
                </div>
            </div>
        </form>
    </div>
</div>