<div class="box grid_12">
    <div class="box-head"><h2>Upload task attachment</h2></div>
    <div class="box-content">
        <form class="form uploadFileForm" action="#" method="post" enctype="multipart/form-data">
            <input type="hidden" name="tk" value="{echo $token}" />
            <input type="hidden" name="MAX_FILE_SIZE" value="10000000"/>
            <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />

            <div class="form-row">
                <p class="form-label">Description*</p>
                <div class="form-item">
                    <textarea cols="85" rows="5" name="description">{echo isset($attachment)? $attachment->description: ""}</textarea>
                </div>
                {if isset($errors["description"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["description"])}</p>
                {/if}
            </div>
            <div class="form-row">
                <p class="form-label">Multi-file upload</p>
                <div class="form-item">
                    <a href="#" class="multi_upload "><span class="icon opsrc add-item"></span></a>
                    <a href="#" class="multi_upload_dec"><span class="icon opsrc delete-item"></span></a>
                </div>
            </div>
            <div class="form-row">
                <p class="form-label">Files</p>
                <div class="form-item file_inputs">
                    <input type="file" name="files[]" />
                </div>
                {if isset($errors["files"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["files"])}</p>
                {/if}
            </div>

            <div class="form-row">
                <div class="form-item">
                    <input type="button" class="button grey" onclick="history.back();" value="Back">
                </div>
            </div>
            <div class="form-row">
                <div class="form-item">
                    <input type="submit" class="button blue" name="uploadFile" value="Upload file"/>
                </div>
            </div>
        </form>
    </div>
</div>