<?php
header('Pragma: public');   // required
header('Expires: 0');       // no cache
header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
header('Cache-Control: private', false);
header('Content-Type: ' . $this->mime);
header('Content-Disposition: attachment; filename="' . basename("." . $this->file['file_path']) . '"');
header('Content-Transfer-Encoding: binary');
header('Content-Length: ' . filesize("." . $this->file['file_path']));    // provide file size
ob_clean();
flush();
readfile("." . $this->file['file_path']);
exit;
?>
