<div class="box-content">
    <div class="form-row">
        <p class="form-label">Title</p>
        <div class="form-item">
            {echo $budget->title}
        </div>
    </div>
    <div class="form-row">
        <p class="form-label">Description</p>
        <div class="form-item">
            {echo $budget->description}
        </div>
    </div>
    <div class="form-row">
        <p class="form-label">Quantity</p>
        <div class="form-item">
            {echo $budget->quantity}
        </div>
    </div>
    <div class="form-row">
        <p class="form-label">Measure units</p>
        <div class="form-item">
            {echo $budget->mu}
        </div>
    </div>
    <div class="form-row">
        <p class="form-label">Price per unit</p>
        <div class="form-item">
            {echo $budget->ppu}
        </div>
    </div>
    <div class="form-row">
        <p class="form-label">Total price</p>
        <div class="form-item">
            {echo $budget->totalPrice}
        </div>
    </div>
</div>