<div class="box grid_12">
    <div class="box-head"><h2>Create new project</h2></div>
    <div class="box-content">
        <form class="form" action="#" method="post">
            <input type="hidden" name="tk" value="{echo $token}" />
            <input type="hidden" name="submstoken" id="submstoken" value="{echo $submstoken}" />
            
            <div class="form-row">
                <p class="form-label">Project name*</p>
                <div class="form-item">
                    <input type="text" name="projname" value="{echo isset($project)? $project->title: ""}" />
                </div>
                {if isset($errors["title"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["title"])}</p>
                {/if}
            </div>

            <div class="form-row">
                <p class="form-label">Description*</p>
                <div class="form-item">
                    <textarea cols="85" rows="5" name="projdesc" id="ckeditor">{echo isset($project)? $project->description: ""}</textarea>
                </div>
                {if isset($errors["description"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["description"])}</p>
                {/if}
            </div>

            <div class="form-row">
                <p class="form-label">Manager*</p>
                <div class="form-item">
                    <select name="manager">
                        {if !empty($managers)}
                            {foreach $manager in $managers}
                                <option value="{echo $manager->getId()}">{echo $manager->getFirstname() . " " . $manager->getLastname()}</option>
                            {/foreach}
                        {/if}{else}
                            <option value="0">No manager found</option>
                        {/else}
                    </select>
                </div>
                {if isset($errors["managerId"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["managerId"])}</p>
                {/if}
            </div>

            <div class="form-row">
                <p class="form-label">Client*</p>
                <div class="form-item">
                    <select name="client">
                        {if !empty($clients)}
                            {foreach $client in $clients}
                                <option value="{echo $client->getId()}">{echo $client->getCompanyName() . " / " . $client->getContactPerson()}</option>
                            {/foreach}
                        {/if}{else}
                            <option value="0">No client found</option>
                        {/else}
                    </select>
                </div>
                {if isset($errors["clientId"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["clientId"])}</p>
                {/if}
            </div>
            <div class="form-row">
                <p class="form-label">Budget</p>
                <div class="form-item">
                    <input type="text" name="budget" value="{echo isset($project)? $project->maxBudget: "0"}" />
                </div>
                {if isset($errors["maxBudget"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["maxBudget"])}</p>
                {/if}
            </div>
            <div class="form-row">
                <p class="form-label">Git repository</p>
                <div class="form-item">
                    <input type="text" name="repository" value="{echo isset($project)? $project->gitRepository: ""}" />
                </div>
                {if isset($errors["gitRepository"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["gitRepository"])}</p>
                {/if}
            </div>
            <div class="form-row">
                <p class="form-label">Task prefix</p>
                <div class="form-item">
                    <input type="text" name="taskprefix" value="{echo isset($project)? $project->taskPrefix: ""}" />
                </div>
                {if isset($errors["taskPrefix"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["taskPrefix"])}</p>
                {/if}
            </div>
            <div class="form-row">
                <p class="form-label">Planned start date *</p>
                <div class="form-item">
                    <input type="text" name="plannedStart" id="datepicker" 
                           value="{echo isset($project)? $project->plannedStart: ""}"/>
                </div>
                {if isset($errors["plannedStart"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["plannedStart"])}</p>
                {/if}
            </div>
            <div class="form-row">
                <p class="form-label">Planned end date *</p>
                <div class="form-item">
                    <input type="text" name="plannedEnd" id="datepicker2" 
                           value="{echo isset($project)? $project->plannedEnd: ""}"/>
                </div>
                {if isset($errors["plannedEnd"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["plannedEnd"])}</p>
                {/if}
            </div>
            <div class="form-row">
                <p class="form-label">Priority *</p>
                <div class="form-item">
                    <select name="priority">
                        <option value="1">1 - Low</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5 - High</option>
                    </select>
                </div>
                {if isset($errors["priority"])}
                    <p class="form-label-error">{echo join("<br/>", $errors["priority"])}</p>
                {/if}
            </div>

            <div class="form-row">
                <div class="form-item">
                    <input type="button" class="button grey" onclick="history.back();" value="Back">
                </div>
            </div>
            <div class="form-row">
                <div class="form-item">
                    <input type="submit" class="button blue" name="submitAddProject" value="Create project"/>
                </div>
            </div>
        </form>
    </div>
</div>