<div class="box-content">
    <form class="form" action="/project/delete/{echo $project->getId()}" method="post">
        <input type="hidden" name="csrf" value="{echo $token}" />
        <div class="form-row">
            <p class="form-label">Project name*</p>
            <div class="form-item">
                {echo $project->getTitle()}
            </div>
        </div>
        <div class="form-row">
            <p class="form-label">Description*</p>
            <div class="form-item">
                {echo $project->getDescription()}
            </div>
        </div>

        <div class="form-row">
            <div class="form-item">
                <input type="submit" class="button red" name="submitDeleteProject" value="Delete project"/>
            </div>
        </div>
    </form>
</div>