<div class="box grid_12">
    <div class="static-header">
        <h3 class="float-left-fixed">{echo $project->getTitle()}</h3>
        <span class="control-buttons float-right-fixed">
            {if $isPM}
                <a class="controll-button-edit" href="/project/edit/{echo $project->getId()}">Edit</a>
                <a class="controll-button-delete ajax-dialog" href="/project/delete/{echo $project->getId()}">Delete</a>
            {/if}
        </span>
    </div>
    <div class="clear-both"></div>
    <input type="hidden" id="tk" name="tk" value="{echo $token}" />

    {if $project->getStateId() == 1}
        <div class="ad-notif-warn grid_12"><p>Project has not been approved yet</p></div>
    {/if}

    {if $isPM}
        <div class="state-button-wrapper">
            {foreach $nextstate in $nextstates}
                <a href="/project/setstate/{echo $project->getId()}/{echo $nextstate->getId()}" class="button blue">
                    {echo $nextstate->getNextStateTitle()}
                </a>
            {/foreach}
            {if !in_array($project->getStateId(), array(1,2,7))}
                <a class="button grey ajax-dialog" href="/budget/add/{echo $project->getId()}">Add budget item</a>
                <a class="button grey" href="/project/uploadattachment/{echo $project->getId()}">Attach file</a>
                <a class="button grey" href="/task/add/{echo $project->getId()}">Create task</a>
                <br/><br/>
            {/if}
        </div>
    {/if}{elseif $isDeveloper}
        <div class="state-button-wrapper">
            {if !in_array($project->getStateId(), array(1,2,7))}
                <a class="button grey" href="/project/uploadattachment/{echo $project->getId()}">Attach file</a>
                <a class="button grey" href="/task/add/{echo $project->getId()}">Create task</a>
                <br/><br/>
            {/if}
        </div>
    {/elseif}{elseif $isClient}
        <div class="state-button-wrapper">
            {if !in_array($project->getStateId(), array(1,2,7))}
                <a class="button grey" href="/project/uploadattachment/{echo $project->getId()}">Attach file</a>
                <br/><br/>
            {/if}
        </div>
    {/elseif}

    <div class="tab-nav grid_7">
        <ul>
            <li><a href="#info">Overview</a></li>
            <li><a href="#chat">Chat</a></li>
            <li><a href="#files">Files</a></li>
            {if $isPM}
                <li><a href="#assignedUsers">Assigned users</a></li>
                <li><a href="#financial">Expences</a></li>
                <li><a href="#timelog">Logged time</a></li>
            {/if}
        </ul>

        <div id="info">
            <div class="box-content">
                <div class="form-row">
                    <p class="form-label">Project name</p>
                    <div class="form-item">{echo $project->getTitle()}</div>
                </div>
                <div class="form-row">
                    <p class="form-label">Description</p>
                    <div class="form-item">{echo $project->getDescription()}</div>
                </div>
                <div class="form-row">
                    <p class="form-label">Manager</p>
                    <div class="form-item">{echo $project->managerFname . " " . $project->managerLname}</div>
                </div>
                <div class="form-row">
                    <p class="form-label">Client</p>
                    <div class="form-item">
                        {if $isDeveloper}
                            <a href="/client/detail/{echo $project->cId}">{echo $project->companyName . " / " . $project->contactPerson}</a>
                        {/if}{else}
                            <a href="/user/profile">{echo $project->companyName . " / " . $project->contactPerson}</a>
                        {/else}
                    </div>
                </div>
                <div class="form-row">
                    <p class="form-label">Budget</p>
                    <div class="form-item">{echo $project->getMaxBudget()." ". $currency}</div>
                </div>
                <div class="form-row">
                    <p class="form-label">Current expenses</p>
                    <div class="form-item">{echo $project->budgetTotal." ". $currency}</div>
                </div>
                <div class="form-row">
                    <p class="form-label">Git repository</p>
                    <div class="form-item">{echo $project->getGitRepository()}</div>
                </div>
                <div class="form-row">
                    <p class="form-label">Paid</p>
                    <div class="form-item">
                        {if $project->getIsPaid() == 1}
                            The project was paid
                        {/if}{else}
                            The project has not been paid yet
                        {/else}
                    </div>
                </div>
                <div class="form-row">
                    <p class="form-label">Progress</p>
                    <div class="form-item">
                        <input type="hidden" name="projprog" id="progressVal" value="{echo $project->getProgress()}" />
                        <div class="progressbar"></div>
                    </div>
                </div>
                <div class="form-row">
                    <p class="form-label">Created</p>
                    <div class="form-item">{echo $project->getCreated()}</div>
                </div>
                <div class="form-row">
                    <p class="form-label">State</p>
                    <div class="form-item">{echo $project->stateTitle}</div>
                </div>
                <div class="form-row">
                    <p class="form-label">Planned start date</p>
                    <div class="form-item">{echo $project->getPlannedStart()}</div>
                </div>
                <div class="form-row">
                    <p class="form-label">Planned end date</p>
                    <div class="form-item">{echo $project->getPlannedEnd()}</div>
                </div>
                <div class="form-row">
                    <p class="form-label">Spent time [d h:m]</p>
                    {script $time = $project->getTotalSpentTime()}
                    <div class="form-item">{echo $time->sptime}</div>
                </div>
                <div class="form-row">
                    <p class="form-label">Priority [1 - Low]</p>
                    <div class="form-item">{echo $project->getPriority()}</div>
                </div>
            </div>
        </div>

        <div id="chat">
            <div class="box-content">
                {if !in_array($project->getStateId(), array(1,2,7))}
                    <form class="projectMessageForm" action="#" method="post">
                        <input type="hidden" name="tk" value="{echo $token}" />
                        <div class="form-row">
                            <p class="form-label">Message title</p>
                            <div class="form-item">
                                <input type="text" name="messtitle" required value="{echo isset($message)? $message->title: ""}"/>
                            </div>
                            {if isset($errors["title"])}
                                <p class="form-label-error">{echo join("<br/>", $errors["title"])}</p>
                            {/if}
                        </div>

                        <div class="form-row">
                            <p class="form-label">Text</p>
                            <div class="form-item">
                                <textarea rows="5" required name="messtext">{echo isset($message)? $message->body: ""}</textarea>
                            </div>
                             {if isset($errors["body"])}
                                <p class="form-label-error">{echo join("<br/>", $errors["body"])}</p>
                            {/if}
                        </div>

                        {if $isDeveloper}
                            <div class="form-row">
                                <p class="form-label">Show to</p>
                                <div class="form-item">
                                    <select name="showto">
                                        <option value="1">Everybody</option>
                                        <option value="2">Developers only</option>
                                    </select>
                                </div>
                            </div>
                        {/if}
                        <div class="form-row">
                            <div class="form-item">
                                <input type="submit" class="button blue" name="submitSendMess" value="Send message"/>
                            </div>
                        </div>
                    </form>
                {/if}
                {script $chat = $project->getChat()}
                {if !empty($chat)}
                    {foreach $message in $chat}
                    <div class="box-content overflow">
                        <div class="message-box">
                            <div class="message-user">{echo $message->fname." ".$message->lname}</div>
                            <div class="message-content">
                                <span class="title">{echo $message->getTitle()}
                                    {if $message->isPublic == 2} - developers only{/if}</span><br/>
                                <span class="created">{echo $message->getCreated()}</span><br/>
                                {echo html_entity_decode($message->getBody())}
                            </div>
                        </div>
                    </div>
                    {/foreach}
                {/if}{else}
                    <div class="box-content">
                        <div class="grid_12 message"><p>No messages available</p></div>
                    </div>
                {/else}
            </div>
        </div>
        
        <div id="files">
            <div class="box-content">
                {script $attachments = $project->getAttachment()}
                {if !empty($attachments)}
                    <ul class="imagelist">
                        {foreach $attch in $attachments}
                        <li>
                            {if $attch->isImage()}
                                <a href="{echo $attch->getPath()}" class="view">
                                    <img src="{echo $attch->getThumbPath()}" alt="{echo $attch->getFilename()}" height="128px" />
                                </a>
                            {/if}{else}
                                <img src="/public/images/fileicon/{echo $attch->getExt()}.png" width="128px" alt="{echo $attch->getDescription()}"/>
                            {/else}
                            <span>
                                <span class="name">{echo substr($attch->getFilename(), 11, strlen($attch->getFilename()))}</span><br/>
                                <a class="download" href="/file/download/{echo $attch->getId()}">Download</a>
                                {if $attch->getUserId() == $authUser->getId() || $isPM}
                                    <a class="delete" href="/file/delete/{echo $attch->getId()}">Delete file</a></li>
                                {/if}
                            </span>
                        </li>
                        {/foreach}
                    </ul>
                {/if}{else}
                    <div class="grid_12 message"><p>No files available</p></div>
                {/else}
            </div>
        </div>

        {if $isPM}
        <div id="assignedUsers">
            <div class="box-head-nohide"><h2>Assigned users</h2></div>
            <div class="box-content no-pad">
                <form method="post" action="/project/assignusers/{echo $project->getId()}">
                    <input type="hidden" name="tk" value="{echo $token}" />
                    <table class="stdtable display">
                        <thead>
                            <tr>
                                <th><input type="checkbox" class="checkall" /></th>
                                <th>Firstname</th><th>Lastname</th>
                            </tr>
                        </thead>
                        <tbody>
                            {if !empty($allusers)}
                                {foreach $user in $allusers}
                                    {script $asch = ""}
                                    {if in_array($user->getId(), $assigneduserids)}
                                        {script $asch = "checked=checked"}
                                    {/if}
                                        
                                    <tr>
                                        <td class="center width100">
                                            <input type="checkbox" {echo $asch} name="projectusersids[]" value="{echo $user->getId()}" />
                                        </td>
                                        <td>{echo $user->getFirstname()}</td>
                                        <td>{echo $user->getLastname()}</td>
                                    </tr>
                                {/foreach}
                            {/if}
                        </tbody>
                    </table>
                    {if !in_array($project->getStateId(), array(1,2,7))}
                        <div class="tableoptions">
                            <input class="button grey" type="submit" name="performProjectUserAction" value="Save selection"/>
                        </div><!--tableoptions-->
                    {/if}
                </form>
            </div>
        </div>
        <div id="financial">
            <div class="box-head-nohide"><h2>Financial records</h2></div>
            <div class="box-content no-pad">
                <table class="stdtable display">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Created</th>
                            <th>Total price</th>
                            <th>Created by</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        {script $budgetC = $project->getBudget()}
                        {if !empty($budgetC)}
                            {foreach $budget in $budgetC}
                                <tr>
                                    <td>{echo $budget->getTitle()}</td>
                                    <td>{echo $budget->getCreated()}</td>
                                    <td>{echo $budget->getTotalPrice()}</td>
                                    <td>{echo $budget->fname." ".$budget->lname}</td>
                                    <td>
                                        <a class="button-detail ajax-dialog" href="/budget/detail/{echo $budget->getId()}">Edit</a>
                                        <a class="button-edit" href="/budget/edit/{echo $budget->getId()}">Edit</a>
                                        <a class="button-delete ajax-dialog" href="/budget/delete/{echo $budget->getId()}">Delete</a>
                                    </td>
                                </tr>
                            {/foreach}
                        {/if}
                    </tbody>
                </table>
            </div>
        </div>
        <div id="timelog">
            <div class="box-head-nohide"><h2>Logged time</h2></div>
            <div class="box-content no-pad">
                <table class="stdtable display">
                    <thead>
                        <tr>
                            <th>Firstname</th>
                            <th>Lastname</th>
                            <th>Spent time [d h:m]</th>
                        </tr>
                    </thead>
                    <tbody>
                        {script $sptime = $project->getTimePerUser()}
                        {if !empty($sptime)}
                            {foreach $tm in $sptime}
                                <tr>
                                    <td>{echo $tm->getFirstname()}</td>
                                    <td>{echo $tm->getLastname()}</td>
                                    <td>{echo date("d H:i", mktime(0, $tm->getSptime(), 0, 0, 0, 0))}</td>
                                </tr>
                            {/foreach}
                        {/if}
                    </tbody>
                </table>
            </div>
        </div>
        {/if}
    </div>
    
    <div class="tab-nav grid_5">
        <ul>
            <li><a href="#tasks">Tasks</a></li>
            <li><a href="#bugs">Bugs</a></li>
            <li><a href="#inquiry">Inquiries</a></li>
        </ul>
        
        <div id="tasks">
            <div class="box-head-nohide"><h2>Tasks</h2></div>
            <div class="box-content no-pad">
                <table class="display">
                    <thead>
                        <tr>
                            <th>Title</th><th>State</th>
                            <th>Created by</th><th>Assigned to</th>
                            <th>Priority</th>
                        </tr>
                    </thead>
                    <tbody>
                        {script $tasks = $project->getTasks()}
                        {if !empty($tasks)}
                            {foreach $task in $tasks}
                                <tr>
                                    <td><a href="/task/{echo $task->getUrlKey()}/">{echo $task->getTitle()}</a></td>
                                    <td>{echo $task->stateTitle}</td>
                                    <td>{echo $task->cFname." ".$task->cLname}</td>
                                    <td>{echo $task->asFname." ".$task->asLname}</td>
                                    <td>{echo $task->getPriority()}</td>
                                </tr>
                            {/foreach}
                        {/if}
                    </tbody>
                </table>
            </div>
        </div>
        <div id="bugs">
            <div class="box-head-nohide"><h2>Bugs</h2></div>
            <div class="box-content no-pad">
                <table class="display">
                    <thead>
                        <tr>
                            <th>Title</th><th>State</th>
                            <th>Created by</th><th>Assigned to</th>
                            <th>Priority</th>
                        </tr>
                    </thead>
                    <tbody>
                        {script $bugs = $project->getBugs()}
                        {if !empty($bugs)}
                            {foreach $bug in $bugs}
                                <tr>
                                    <td><a href="/task/{echo $bug->getUrlKey()}/">{echo $bug->getTitle()}</a></td>
                                    <td>{echo $bug->stateTitle}</td>
                                    <td>{echo $bug->cFname." ".$bug->cLname}</td>
                                    <td>{echo $bug->asFname." ".$bug->asLname}</td>
                                    <td>{echo $bug->getPriority()}</td>
                                </tr>
                            {/foreach}
                        {/if}
                    </tbody>
                </table>
            </div>
        </div>
        <div id="inquiry">
            <div class="box-head-nohide"><h2>Inquiries</h2></div>
            <div class="box-content no-pad">
                <table class="display">
                    <thead>
                        <tr>
                            <th>Title</th><th>State</th>
                            <th>Created by</th><th>Assigned to</th>
                            <th>Priority</th>
                        </tr>
                    </thead>
                    <tbody>
                        {script $inquiries = $project->getInquiries()}
                        {if !empty($inquiries)}
                            {foreach $inq in $inquiries}
                                <tr>
                                    <td><a href="/task/{echo $inq->getUrlKey()}/">{echo $inq->getTitle()}</a></td>
                                    <td>{echo $inq->stateTitle}</td>
                                    <td>{echo $inq->cFname." ".$inq->cLname}</td>
                                    <td>{echo $inq->asFname." ".$inq->asLname}</td>
                                    <td>{echo $inq->getPriority()}</td>
                                </tr>
                            {/foreach}
                        {/if}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>        